/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package LcmGui;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class Header implements lcm.lcm.LCMEncodable
{
    public long sec;
    public int nsec;
 
    public Header()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xde1d24a3a8e0be48L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(LcmGui.Header.class))
            return 0L;
 
        classes.add(LcmGui.Header.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.sec); 
 
        outs.writeInt(this.nsec); 
 
    }
 
    public Header(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public Header(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static LcmGui.Header _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        LcmGui.Header o = new LcmGui.Header();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.sec = ins.readLong();
 
        this.nsec = ins.readInt();
 
    }
 
    public LcmGui.Header copy()
    {
        LcmGui.Header outobj = new LcmGui.Header();
        outobj.sec = this.sec;
 
        outobj.nsec = this.nsec;
 
        return outobj;
    }
 
}

